apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: us.gcr.io/ticketing-dev-504919/auth-service
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: COOKIE_SECURE
              value: 'false'
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-srv
spec:
  selector:
    app: auth-service
  ports:
    - name: auth-service
      protocol: TCP
      port: 8000
      targetPort: 8000
