apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tickets-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-service
  template:
    metadata:
      labels:
        app: tickets-service
    spec:
      containers:
        - name: tickets-service
          image: us.gcr.io/ticketing-dev-504919/tickets-service
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: COOKIE_SECURE
              value: 'false'
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service-srv
spec:
  selector:
    app: tickets-service
  ports:
    - name: tickets-service
      protocol: TCP
      port: 8000
      targetPort: 8000
