name: tickets-service tests

on:
  pull_request:
    paths:
      - 'tickets-service/**'
      - '.github/workflows/tickets-service-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
        working-directory: tickets-service
      - run: npm run test:ci
        working-directory: tickets-service
